# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Description is in document head meta (for Google search results) and in your feed.xml site description

# Site settings
title: RoyOwl
tagline:
email: ''
description: > # this means ignore newlines until "baseurl:"
  Recommending simple, durable products for life; free shipping from <a target="_blank" href="https://www.amazon.com/tryprimefree?ref_=assoc_tag_ph_1427739975520&_encoding=UTF8&camp=1789&creative=9325&linkCode=pf4&tag=royowl-20&linkId=ca5c36f8fe74cf957fd5873798eb5e9f">Amazon Prime</a>.
  Tested in the mountains, trails, and rivers of <a href="https://goo.gl/maps/KLmL3C4x34u">Jackson Hole, Wyoming</a>.
baseurl: / # the subpath of your site, e.g. /blog
url: "http://royowl.net" # the base hostname & protocol for your site

author:
  name:           ''
  url:            ''

gems: [jekyll-paginate]
paginate: 5

# Dependencies
markdown:         kramdown
highlighter:      rouge
